### ISSUE TITLE
Content Team Requests

### ISSUE THREAD

**Issue by johnsiwicki** [bs-production/treehouse-design-system#4]
**New image slider** - http://watercare.basementsite.com/products/softeners/caresoft-elite.html

**Side by side imag**es - http://coredev.basementsite.com/concrete-leveling/concrete-lifting-examples.html

**Resizing image breakout (used if image is smaller or larger than 300px) - Example:** 

```html
<div class="breakout right border bg" style=“width: 400px;”>
  <a href="http://placehold.it/400/300" class="lightbox right" title=""><img src="http://placehold.it/400x214" alt="" width="" height="" /></a>
  <p>Add CAP HERE</p>
</div>
``` 

**Rows and columns** - http://coredev.basementsite.com/concrete-repair.html

**Before and after image slid**ers - http://coredev.basementsite.com/concrete-leveling.html - I’m not sure if we could easily add this to the style guide, since there are two separate pieces of code to add: one in the custom code module and one in the <head> under advanced options

**Double lists** - Melissa noticed that if you don’t add a “clear” after the last div then it breaks whatever comes after the double list. Is there a better way to fix this? If not, we should add the clear code to the style guide so that everyone knows to add it.

**Adding images without a breakout** - Is this a no no or is it ok to do?

**Comment by chrisroselli** [comment]
Added these, other than New image slider. It needs a bunch of stuff like custom slick slider.

**Comment by johnsiwicki** [comment]
Should we close?

**Comment by chrisroselli** [comment]
I'll take one more look then close.
