### ISSUE TITLE
Merge The Two Systems

### ISSUE THREAD

**Issue by johnsiwicki** [bs-production/treehouse-design-system#5]
Should we keep this alive or merge it with this?  https://bs-production.github.io/web-production-resources/#/

**Comment by chrisroselli** [comment]
I like the idea of merging the two systems. Once we get a firm grip on the new Fractal system, I will begin drawing up a plan to bring over web production resources.

**Comment by johnsiwicki** [comment]
We can keep Fractal private and have an issues on repo for the team?

**Comment by chrisroselli** [comment]
Resources brought over.
